export const PREDEFINED_GENRES = [
  'Fiction',
  'Non-Fiction',
  'Sci-Fi',
  'Fantasy',
  'Mystery',
  'Thriller',
  'Romance',
  'Horror',
  'Biography',
  'Self-Help',
  'History',
  'Science',
  'Philosophy',
  'Business',
  'Travel',
  'Young Adult',
  "Children's",
  'Poetry',
  'Graphic Novel',
] as const;